import de.hamster.debugger.model.Territorium;import de.hamster.debugger.model.Territory;import de.hamster.model.HamsterException;import de.hamster.model.HamsterInitialisierungsException;import de.hamster.model.HamsterNichtInitialisiertException;import de.hamster.model.KachelLeerException;import de.hamster.model.MauerDaException;import de.hamster.model.MaulLeerException;import de.hamster.model.MouthEmptyException;import de.hamster.model.WallInFrontException;import de.hamster.model.TileEmptyException;public class Aufgabe2_1 extends de.hamster.debugger.model.IHamster implements de.hamster.model.HamsterProgram {public void main() {
	// hoch
    vor();
    linksUm();
    vor();
	linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    // wieder runter
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    vor();
    linksUm();
    linksUm();
    linksUm();
    vor();
    linksUm();
    
}
}